/**
 * Bundle app/main.ts with esbuild, inline it and the viewer's stylesheet into
 * app/template.html, and write src/app-bundle.generated.ts: one string the
 * server serves as the ui:// resource. Committed, so nothing builds at run
 * time; re-run after changing app/ or the viewer's stylesheet.
 *
 *     npx tsx scripts/build-app.ts
 */
import { build } from "esbuild";
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { stylesheet } from "../../viewer/render.ts";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");

const result = await build({
  entryPoints: [join(root, "app", "main.ts")],
  bundle: true,
  format: "esm",
  platform: "browser",
  target: "es2022",
  minify: true,
  write: false,
  legalComments: "none",
});
const script = result.outputFiles[0]!.text.replace(/<\/script/gi, "<\\/script");
const html = readFileSync(join(root, "app", "template.html"), "utf8")
  .replace("/*STYLE*/", () => stylesheet())
  .replace("/*SCRIPT*/", () => script);

const out = `// GENERATED by scripts/build-app.ts from app/ and the viewer's stylesheet. Do not edit.
export const APP_HTML = ${JSON.stringify(html)};
`;
writeFileSync(join(root, "src", "app-bundle.generated.ts"), out, "utf8");
console.log(`app bundle: ${(html.length / 1024).toFixed(0)} KB (script ${(script.length / 1024).toFixed(0)} KB)`);
